[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = ["@openzepplin/contracts=lib/openzepplin-contracts/contracts"]
[lint]
# ... rest of lint config ...
exclude_lints = ["mixed-case-function","mixed-case-variable"]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
